# Generated by Django 2.1.2 on 2018-10-05 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='f_name',
            new_name='first_name',
        ),
    ]
